name: check-links
on:
  push:
    branches: [ main ]
  pull_request:

# Do not cancel this workflow on main. See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16616
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  # renovate: datasource=github-releases depName=tcort/markdown-link-check
  MD_LINK_CHECK_VERSION: "3.12.2"

jobs:
  changedfiles:
    name: changed files
    runs-on: ubuntu-latest
    env:
      PR_HEAD: ${{ github.event.pull_request.head.sha }}
    if: ${{ github.actor != 'dependabot[bot]' }}
    outputs:
      md: ${{ steps.changes.outputs.md }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changes
        run: |
          md=$(git diff --name-only --diff-filter=ACMRTUXB $(git merge-base origin/main $PR_HEAD) $PR_HEAD | grep .md$ | xargs)

          md_link_check_version_change=$(git diff origin/main -- .github/workflows/check-links.yaml $(git merge-base origin/main $PR_HEAD) $PR_HEAD | grep -E '^[\+\-]\s*MD_LINK_CHECK_VERSION:' || echo "")
          if [ -z "$md" ] && [[ -n "$md_link_check_version_change" ]]; then
            md="**/*.md"
          fi

          echo "md=$md" >> $GITHUB_OUTPUT
  check-links:
    runs-on: ubuntu-latest
    needs: changedfiles
    if: ${{needs.changedfiles.outputs.md}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install markdown-link-check
        run: npm install -g markdown-link-check@${{ env.MD_LINK_CHECK_VERSION }}

      - name: Run markdown-link-check
        run: |
          markdown-link-check \
            --verbose \
            --config .github/workflows/check_links_config.json \
            ${{needs.changedfiles.outputs.md}} \
            || { echo "Check that anchor links are lowercase"; exit 1; }