name: check-links
on:
  push:
    branches: [ main ]
  pull_request:

# Do not cancel this workflow on main. See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16616
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  # renovate: datasource=github-releases depName=tcort/markdown-link-check
  MD_LINK_CHECK_VERSION: "3.12.2"
  MD_FILES: "./"

jobs:
  changedfiles:
    name: changed files
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    outputs:
      any_changed: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **.md
            .github/workflows/check-links.yaml
  check-links:
    runs-on: ubuntu-latest
    needs: changedfiles
    if: ${{needs.changedfiles.outputs.any_changed}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install markdown-link-check
        run: npm install -g markdown-link-check@${{ env.MD_LINK_CHECK_VERSION }}

      - name: Run markdown-link-check
        run: |
          markdown-link-check \
            --verbose \
            --config .github/workflows/check_links_config.json \
            ${{ env.MD_FILES }} \
            || { echo "Check that anchor links are lowercase"; exit 1; }
